2024-05-16 00:29:07,530 INFO    MainThread:76540 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-16 00:29:07,530 INFO    MainThread:76540 [wandb_setup.py:_flush():76] Configure stats pid to 76540
2024-05-16 00:29:07,530 INFO    MainThread:76540 [wandb_setup.py:_flush():76] Loading settings from /Users/binliu/.config/wandb/settings
2024-05-16 00:29:07,531 INFO    MainThread:76540 [wandb_setup.py:_flush():76] Loading settings from /Users/binliu/Documents/small_nice/wandb/wandb_proj/wandb/settings
2024-05-16 00:29:07,531 INFO    MainThread:76540 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-16 00:29:07,531 INFO    MainThread:76540 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-16 00:29:07,531 INFO    MainThread:76540 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'wandb_proj/test.py', 'program_abspath': '/Users/binliu/Documents/small_nice/wandb/wandb_proj/test.py', 'program': '/Users/binliu/Documents/small_nice/wandb/wandb_proj/test.py'}
2024-05-16 00:29:07,531 INFO    MainThread:76540 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-16 00:29:07,531 INFO    MainThread:76540 [wandb_init.py:_log_setup():520] Logging user logs to /Users/binliu/Documents/small_nice/wandb/wandb_proj/wandb/run-20240516_002907-5fowbh69/logs/debug.log
2024-05-16 00:29:07,531 INFO    MainThread:76540 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/binliu/Documents/small_nice/wandb/wandb_proj/wandb/run-20240516_002907-5fowbh69/logs/debug-internal.log
2024-05-16 00:29:07,531 INFO    MainThread:76540 [wandb_init.py:init():560] calling init triggers
2024-05-16 00:29:07,532 INFO    MainThread:76540 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2024-05-16 00:29:07,532 INFO    MainThread:76540 [wandb_init.py:init():610] starting backend
2024-05-16 00:29:07,532 INFO    MainThread:76540 [wandb_init.py:init():614] setting up manager
2024-05-16 00:29:07,534 INFO    MainThread:76540 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-16 00:29:07,536 INFO    MainThread:76540 [wandb_init.py:init():622] backend started and connected
2024-05-16 00:29:07,539 INFO    MainThread:76540 [wandb_init.py:init():711] updated telemetry
2024-05-16 00:29:07,562 INFO    MainThread:76540 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-16 00:29:07,757 ERROR   MainThread:76540 [wandb_init.py:init():770] encountered error: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2024-05-16 00:29:07,758 ERROR   MainThread:76540 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/Users/binliu/.pyenv/versions/3.12.2/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/binliu/.pyenv/versions/3.12.2/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.AuthenticationError: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2024-05-16 00:29:09,153 WARNING MsgRouterThr:76540 [router.py:message_loop():77] message_loop has been closed
